### ISSUE TITLE
to_xml joint type

### ISSUE THREAD

**Issue by zt-yang** [Learning-and-Intelligent-Systems/lisdf#6]
if I write a "revolute" joint type in SDF+, it becomes "hinge" in to_xml(), which causes an error when loading into pybullet

if I write a "fixed" joint in SDF+, parsing gives me error:

```
Traceback (most recent call last):
  File "/Users/z/Documents/simulators/PyBullet/kitchen-worlds/pybullet_lisdf.py", line 65, in <module>
    world = load_lisdf_pybullet(sdf_path)
  File "/Users/z/Documents/simulators/PyBullet/kitchen-worlds/pybullet_lisdf.py", line 39, in load_lisdf_pybullet
    world = load_sdf(sdf_path).worlds[0]
  File "/Users/z/Documents/simulators/PyBullet/kitchen-worlds/lisdf/parsing/sdf_j.py", line 378, in load_sdf
    return visitor.load_file(filename).data
  File "/Users/z/Documents/simulators/PyBullet/kitchen-worlds/lisdf/parsing/xml_j/visitor.py", line 39, in load_file
    return self.visit(filename, node)
  File "/Users/z/Documents/simulators/PyBullet/kitchen-worlds/lisdf/parsing/xml_j/visitor.py", line 75, in visit
    return _inner(root)
  File "/Users/z/Documents/simulators/PyBullet/kitchen-worlds/lisdf/parsing/xml_j/visitor.py", line 58, in _inner
    node.children[i] = _inner(c)
  File "/Users/z/Documents/simulators/PyBullet/kitchen-worlds/lisdf/parsing/xml_j/visitor.py", line 58, in _inner
    node.children[i] = _inner(c)
  File "/Users/z/Documents/simulators/PyBullet/kitchen-worlds/lisdf/parsing/xml_j/visitor.py", line 58, in _inner
    node.children[i] = _inner(c)
  File "/Users/z/Documents/simulators/PyBullet/kitchen-worlds/lisdf/parsing/xml_j/visitor.py", line 66, in _inner
    return proc(node)
  File "/Users/z/Documents/simulators/PyBullet/kitchen-worlds/lisdf/parsing/xml_j/visitor.py", line 132, in wrapped
    assert len(rv.children) == 0
AssertionError
numActiveThreads = 0
stopping threads
destroy semaphore
semaphore destroyed
Thread with taskId 0 exiting
Thread TERMINATED
destroy main semaphore
main semaphore destroyed

Process finished with exit code 1
```

**Comment by vacancy** [comment]
Already fixed in the latest commits in branch Jiayuan
